### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by carpedm20** [Daewon-Hwang/MultiviewSMPLFitting_Motec#1]

**Comment by Daewon-Hwang** [comment]
반갑습니다. 저는 인공지능연구원에서 일반 영상에서 사람의 몸, 손동작을 모션캡쳐 하는 연구를 진행하구 있구요, 최종적으로 캐릭터에 리타게팅하여 애니메이션을 생성하는 기술을 개발하고 있습니다.  이와 관련해서 서비스를 기획중인 단계에 있습니다. 추가적으로 궁금하신 사항은 메일 주시면 답변드리겠습니다. dwhwang@airi.kr
